osx_image: xcode9.2
os: osx
sudo: required

language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"

before_cache:
  - rm -rf node_modules/.yarn-integrity

before_install:
  - if [ -z "$TRAVIS_TAG" ]; then
      export TRAVIS_TAG=0.0.0-dev;
    fi

install:
  - yarn global add xvfb-maybe
  - MYSTERIUM_CLIENT_PREVENT_LOCAL_INSTALL=true yarn

jobs:
  include:
    - stage: Test
      script:
        - yarn ci

    - stage: Update 0.0.0-dev
      if: type != pull_request AND branch = master AND tag IS blank
      script:
        - git tag -f $TRAVIS_TAG
        - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_API_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git push -f gh $TRAVIS_TAG

    - stage: Deploy
      if: tag IS present
      script: skip
      before_deploy:
        - bash util_scripts/travis-number.sh
        - mkdir releases
        # OS X
        - FORCE_DOWNLOAD=1 yarn download:bins:osx
        - yarn build
        - cp build/MysteriumVPN-*.dmg releases/MysteriumVPN.dmg
        # Windows
        - FORCE_DOWNLOAD=1 yarn download:bins:win
        - yarn build:win
        - cp build/MysteriumVPN\ Setup\ *.exe releases/MysteriumVPN.exe
      deploy:
        # Release (tags)
        - provider: releases
          file_glob: true
          file: releases/*
          skip_cleanup: true
          api_key: "$GITHUB_API_TOKEN"
          on:
            tags: true

notifications:
  slack:
    rooms:
      - secure: >
          MRTSnzKnwmkxR4yz74eT6Cp1lyIZjlAvRssiaFr+OmtQcQlRmmCayKeUSygvaUHrNQgLuc5dzv1DKsdSb/qAE0To+3C3VE+wrZvtw+KyrYIzxG
          GQdcNviP5DaTqNo1ah15Vw5Cac823F6K7HIDgBpj2u8dN4R/JEtL52dY8MSRXIGu5IBqxDOA0gpQa+lP4UzRCRo3dx8PvisCx9JhPR0AoPjDOp
          luXZjigB5qtqrzB7XczvUXJVMdTm6YXyBT1R3xyQri/77RVEPB/LHFMxNl/ntDVQUb8Wyw+Oyc/mbRjbbNdPaWZAsVqkdUy7f49ZPg91Ja+wwr
          L5waUkwiYjeVe/cHLwSVaiAhCS51li0ura1CLKMxF6kBohy6GnRMdJlUE4Yf54uCECKpA+4YVFyCC1/E0h1D6kIvDxpa/mqven2oQwBoh7jz27
          JIsTVPlMF/b1swlL+Bt5zqxx+IHyrDmIylLyWhMBBtZ4IO5JLgXP9RIP5Bd/CPfFQcdB13/fN1y8cOP6V7aK4Yjoa3NA0MLeHkZx5JeP1lgtrn
          IdM3dB9yo4qiA3y+qzPo8fawW715HRHNlgLnWtT5fAswEECDLCQnUaFLAzrVQmpQXuGK3hJHvBIEjh/NLbQsJ6OVzDGc4kthZSVU2Uq516KiD5
          7aGX4NEmu2sFxuuYdiyhaBU=
    on_success: change
    on_failure: always
